### ISSUE TITLE
targetIdentifier support for belongsTo association

### ISSUE THREAD

**Issue by razmat145** [mkunft/sequelize-oracle#6]
When belongsTo happens, the query generator needs to check if there's a targetIdentifier attribute on the association.

I definitely need to check this with you.

A quick hack that I've found is to change the attrRight assignment like this:
```
attrRight = association.associationType !== 'BelongsTo' ?
        association.identifierField || association.identifier :
        association.targetIdentifier || right.rawAttributes[primaryKeysRight[0]].field || primaryKeysRight[0]
```

https://github.com/mkunft/sequelize-oracle/blob/601e6d760114a47e9fd275acfa1799c4c3538c9d/lib/dialects/oracle/query-generator.js#L788

**Comment by pe1te3son** [comment]
Solved in commit [5a90963](/mkunft/sequelize-oracle/pull/10/commits/5a909636a790c5c835deba5ad9b4df13fd9ceb31)
